name: CI-CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Build Successful"

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - run: echo "Deploy Successful"